# Generated by Django 5.0 on 2023-12-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icerik', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='onayli_mi',
            field=models.BooleanField(default=False),
        ),
    ]
