# Generated by Django 5.0 on 2023-12-12 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icerik', '0004_remove_teacher_onayli_mi'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='onaylanmis',
            field=models.BooleanField(default=False),
        ),
    ]
