# Generated by Django 5.0 on 2023-12-12 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icerik', '0005_teacher_onaylanmis'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnayBekleyenIcerik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onay_durumu', models.BooleanField(default=False)),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='icerik.teacher')),
            ],
        ),
    ]
