# Generated by Django 5.0 on 2023-12-12 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icerik', '0006_onaybekleyenicerik'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='onaylanmis',
        ),
        migrations.DeleteModel(
            name='OnayBekleyenIcerik',
        ),
    ]
