# Generated by Django 5.0 on 2023-12-12 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icerik', '0007_remove_teacher_onaylanmis_delete_onaybekleyenicerik'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='onaylandi',
            field=models.BooleanField(default=False),
        ),
    ]
