# Generated by Django 5.0 on 2023-12-12 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icerik', '0008_teacher_onaylandi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'permissions': [('can_change_approval_status', 'Can Change Approval Status')]},
        ),
    ]
