# Generated by Django 5.0 on 2023-12-12 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icerik', '0009_alter_teacher_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={},
        ),
    ]
