# Generated by Django 5.0 on 2023-12-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icerik', '0012_teacher_onayli'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='onayli',
            field=models.BooleanField(default=False, verbose_name='YÖNETİCİLER ONAYLAYACAKTIR DOKUNMAYINIZ!'),
        ),
    ]
