# Generated by Django 5.0 on 2023-12-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icerik', '0013_alter_teacher_onayli'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='onayli',
            field=models.BooleanField(default=False, verbose_name='Yönetici Onay Butonu!'),
        ),
    ]
