# Generated by Django 5.0 on 2023-12-13 08:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icerik', '0014_alter_teacher_onayli'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='icerikyazi',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='icerikyazi2',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='icerikyazi3',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='icerikyazi4',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='icerikyazi5',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='icerikyazi6',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='icerikyazi7',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
