# Generated by Django 5.0 on 2023-12-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icerik', '0015_alter_teacher_icerikyazi_alter_teacher_icerikyazi2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
