# Generated by Django 5.0 on 2023-12-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icerik', '0016_teacher_is_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='is_new',
            field=models.BooleanField(default=True, verbose_name='Yeni içerik ise tik at!'),
        ),
    ]
