# Generated by Django 5.0 on 2023-12-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icerik', '0017_alter_teacher_is_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='is_new',
            field=models.BooleanField(default=True, verbose_name='YENİ İÇERİK İSE TİK AT, HER YENİ İÇERİK EKLENDİĞİNDE ÖNCEKİ KALDIRILMALI!'),
        ),
    ]
