# Generated by Django 5.0 on 2023-12-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icerik', '0018_alter_teacher_is_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='onayli',
            field=models.BooleanField(default=False, verbose_name='YÖNETİCİ ONAY BUTONU!'),
        ),
    ]
