# Generated by Django 5.0 on 2023-12-18 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icerik', '0020_alter_teacher_is_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='video',
            field=models.FileField(default='None', upload_to='videos/', verbose_name='SADECE MP4 FORMATINDA YÜKLEME YAPINIZ!'),
        ),
    ]
