# Generated by Django 5.0 on 2023-12-18 08:57

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icerik', '0021_alter_teacher_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='derece',
            field=models.CharField(choices=[('Basit', 'Basit'), ('Orta', 'Orta'), ('Zor', 'Zor')], max_length=20, verbose_name='Zorluk Derecesi'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='icerikbaslik',
            field=models.CharField(default='Hazırla', max_length=100, verbose_name='Hazırla Bölüm Başlığı'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='icerikbaslik2',
            field=models.CharField(default='İlgi Uyandırma', max_length=100, verbose_name='İlgi Uyandırma Bölüm Başlığı'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='icerikbaslik3',
            field=models.CharField(default='Keşfet ve Deneyimle', max_length=100, verbose_name='Keşfet ve Deneyimle Bölüm Başlığı'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='icerikbaslik4',
            field=models.CharField(default='Keşfet ve Tasarla', max_length=100, verbose_name='Keşfet ve Tasarla Bölüm Başlığı'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='icerikbaslik5',
            field=models.CharField(default='Kodla ve Deneyimle', max_length=100, verbose_name='Kodla ve Deneyimle Bölüm Başlığı'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='icerikbaslik6',
            field=models.CharField(default='Farklılaştırma', max_length=100, verbose_name='Farklılaştırma Bölüm Başlığı'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='icerikbaslik7',
            field=models.CharField(default='Eklenti', max_length=100, verbose_name='Eklenti Bölüm Başlığı'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='icerikyazi',
            field=ckeditor.fields.RichTextField(verbose_name='Hazırla Bölüm İçeriği'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='icerikyazi2',
            field=ckeditor.fields.RichTextField(verbose_name='İlgi Uyandırma Bölüm İçeriği'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='icerikyazi3',
            field=ckeditor.fields.RichTextField(verbose_name='Keşfet ve Deneyimle Bölüm İçeriği'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='icerikyazi4',
            field=ckeditor.fields.RichTextField(verbose_name='Keşfet ve Tasarla Bölüm İçeriği'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='icerikyazi5',
            field=ckeditor.fields.RichTextField(verbose_name='Kodla ve Deneyimle Bölüm İçeriği'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='icerikyazi6',
            field=ckeditor.fields.RichTextField(verbose_name='Farklılaştırma Bölüm İçeriği'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='icerikyazi7',
            field=ckeditor.fields.RichTextField(verbose_name='Eklenti Bölüm İçeriği'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='kodrehberkapak',
            field=models.ImageField(default='None', upload_to='images/kod/kapak/', verbose_name='Kod Rehber Kapağı'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='sinif',
            field=models.CharField(choices=[('Okul Öncesi', 'Okul Öncesi'), ('1-2. Sınıf', '1-2. Sınıf'), ('1-8. Sınıf', '1-5. Sınıf'), ('6-8. Sınıf', '6-8. Sınıf'), ('Tüm Sınıflar', 'Tüm Sınıflar')], default='Okul Öncesi', max_length=20, verbose_name='Sınıf Aralığı'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='sure',
            field=models.CharField(default='45', max_length=3, verbose_name='Ders Süresi'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='tasarimrehberkapak',
            field=models.ImageField(default='None', upload_to='images/kapak/', verbose_name='Tasarım Rehber Kapağı'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='video',
            field=models.FileField(default='None', upload_to='videos/', verbose_name='MP4 Video'),
        ),
    ]
