# Generated by Django 5.0 on 2023-12-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icerik', '0022_alter_teacher_derece_alter_teacher_icerikbaslik_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='icerikanabaslik',
            field=models.CharField(default='Buraya İçeriğin Ana Başlığı Giriniz!', max_length=100, verbose_name='İçerik Ana Başlığı'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='İçerik Kapak Fotoğrafı'),
        ),
    ]
