# Generated by Django 5.0 on 2023-12-18 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icerik', '0023_alter_teacher_icerikanabaslik_alter_teacher_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
