# Generated by Django 5.0 on 2023-12-18 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icerik', '0025_alter_teacher_options_teacher_created'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kid',
        ),
    ]
