# Generated by Django 5.0 on 2023-12-18 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icerik', '0026_delete_kid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['-created'], 'verbose_name': 'Deneme', 'verbose_name_plural': 'Deneme3842'},
        ),
    ]
