# Generated by Django 5.0 on 2023-12-19 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icerik', '0028_alter_teacher_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default="URL'yi Buradan Değiştir!", max_length=50)),
                ('pinoostudio', models.URLField(blank=True, null=True)),
                ('pinoocode', models.URLField(blank=True, null=True)),
                ('windows', models.URLField(blank=True, null=True)),
                ('linux', models.URLField(blank=True, null=True)),
                ('macos', models.URLField(blank=True, null=True)),
                ('ios', models.URLField(blank=True, null=True)),
                ('google', models.URLField(blank=True, null=True)),
                ('android', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
