# Generated by Django 5.0 on 2023-12-19 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icerik', '0030_teacher_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='pdf_file',
        ),
    ]
