# Generated by Django 5.0 on 2023-12-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icerik', '0031_remove_teacher_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='kodrehberkapak',
            field=models.FileField(default='None', upload_to='images/kod/kapak/', verbose_name='Kod Rehber Kapağı'),
        ),
    ]
