# Generated by Django 5.0 on 2023-12-25 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icerik', '0032_alter_teacher_kodrehberkapak'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='tasarimrehberkapak',
        ),
    ]
