# Generated by Django 5.0 on 2023-12-25 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icerik', '0033_remove_teacher_tasarimrehberkapak'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='tasarimrehberkapak',
            field=models.ManyToManyField(to='icerik.teacher'),
        ),
    ]
