# Generated by Django 5.0 on 2023-12-25 10:56

import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icerik', '0038_remove_teacher_images_alter_teacher_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='images',
            field=imagekit.models.fields.ProcessedImageField(default='None', upload_to='teachers/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='İçerik Kapak Fotoğrafı'),
        ),
    ]
