# Generated by Django 5.0 on 2023-12-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icerik', '0039_teacher_images_alter_teacher_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='images',
        ),
        migrations.AddField(
            model_name='teacher',
            name='images',
            field=models.ManyToManyField(to='icerik.image'),
        ),
    ]
