# Generated by Django 5.0 on 2023-12-26 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icerik', '0040_remove_image_image2_remove_image_image3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='images',
        ),
        migrations.AddField(
            model_name='teacher',
            name='tasarimrehberkapak',
            field=models.FileField(default='None', upload_to='images/kod/kapak/', verbose_name='Kod Rehber Kapağı'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
