# Generated by Django 5.0 on 2023-12-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icerik', '0041_remove_teacher_images_teacher_tasarimrehberkapak_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='onaylimi',
            field=models.BooleanField(default=False, verbose_name='YÖNETİCİ ONAY BUTONU!'),
        ),
    ]
