# Generated by Django 5.0 on 2023-12-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icerik', '0043_teacher_ekkaynak_teacher_gereklimateryal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='onayli',
            field=models.BooleanField(default=False, verbose_name='Öğretmen İçerik Onayı!'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='onaylimi',
            field=models.BooleanField(default=False, verbose_name='Öğrenci İçerik Onayı!'),
        ),
    ]
