# Generated by Django 5.0 on 2024-01-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icerik', '0044_alter_teacher_onayli_alter_teacher_onaylimi'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='zip_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
