# Generated by Django 5.0 on 2024-01-15 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icerik', '0045_teacher_zip_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='custom_zip_file',
            field=models.FileField(blank=True, null=True, upload_to='custom_uploads/'),
        ),
    ]
